title:             Aezlo's Blog
email:             hello@athelo.net
description:       The Blog of Aezlo
author:            Aezlo
baseurl:           "/blog"
url:               "http://athelo.net"

# Social Profiles
twitter_username:  axlelr
github_username:   aez0
facebook_username: #

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
