title:             Aezlo's Blog
email:             hello@athelo.net
description:       The Blog of Aezlo
author:            Aezlo
baseurl:           "/blog"
url:               "aezx.a.b.c.d.e.f.g.h.i.j.k.l.m.n.o.p.q.r.s.t.u.v.w.x.y.z.athelo.net"

# Social Profiles
twitter_username:  axlelr
github_username:   aez0
facebook_username: #

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
